name: Deployment

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Which package to release'
        required: true
        type: choice
        options:
        - uefi-macros
        - uefi-rs
        - uefi-services
      version:
        description: 'New version number'
        required: true
        type: string

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: publish
        run: echo 'I am pretending to publish stuff! ${{ github.event.inputs.package }}: v${{ github.event.inputs.version }}'
