name: Deployment

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Which package to release'
        required: true
        default: 'warning'
        type: choice
        options:
        - uefi-macros
        - uefi-rs
        - uefi-services

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: publish
        run: echo 'I am pretending to publish stuff!'
